### ISSUE TITLE
Stuff that can be improved

### ISSUE THREAD

**Issue by ArielJGS** [EngineerMark/OsuAchievedOverlay#13]
Alright time to bother you with more stuff that maybe you can fix to make your tool even better:
1) When you change the update rate in the settings the update bar seems to not work properly until you restart the tool.
2) Well I think this would be a nice addition because yesterday I almost fucked it up... The start a new session button should have a confirmation prompt just in case you hit it by mistake xD
3) The dropdown menu in the settings tab/gamemode looks weird with a white background, I think it can be improved.
4) Maybe you can add a "Get your API" button to the Fix API window for those who don't know how to get it.

**Comment by EngineerMark** [comment]
API links added in 1e6c7ef852d42a2933bda4ef5b906757f0c5ed72

![image](https://user-images.githubusercontent.com/25825983/116130017-06590000-a6cb-11eb-82a6-11702d40db04.png)

**Comment by EngineerMark** [comment]
Dropdown controls fixed in bc3a3d1255ab2b1783c801cfcd896f8137297f54

![image](https://user-images.githubusercontent.com/25825983/116138149-bbdc8100-a6d4-11eb-89e5-8484b87d0a31.png)

**Comment by EngineerMark** [comment]
Warning prompt new session added in 7c6151d112aefbb9fe41fe17d2d942640cb1c97d

**Comment by EngineerMark** [comment]
3rd attempt I think on fixing the progress bar, here goes nothing; 6cf6d2f11ff63dbc7018ea0c47965363762afc84
