### ISSUE TITLE
Add the ability to hide/show stats

### ISSUE THREAD

**Issue by WitherFlower** [EngineerMark/OsuAchievedOverlay#16]
I'd like to be able to no see certain stats, such as pp, pp rank, and accuracy, but there's currently no way to hide these stats.
I've not made the switch from osu!Profile to osu!Achieved because it lacks this feature.

**Comment by EngineerMark** [comment]
This is already a feature in the upcoming 2.0!
Although it will take a bit before it comes out, you can compile a build on the `dev` branch already and use that one.

Readme has also been updated on that branch to contain a guide to building it yourself.

**Comment by WitherFlower** [comment]
I have no idea how to make visual studio do what I want so I'll just wait for the update
