### ISSUE TITLE
OBS Studios won't capture the overlay

### ISSUE THREAD

**Issue by hyperrdubb** [EngineerMark/OsuAchievedOverlay#22]
Hello, I'm not sure if others have this as an occurring problem or it's just me but whenever I try to capture the overlay, It wouldn't see it. It knows it's there and changed the resolution to fit the overlay but it's just a black screen.

I tried Game Capture and nothing worked and then I tried Windows Capture and still a black screen. I have the latest version of OBS Studios and the Overlay, so I'm not sure where it went wrong. I have everything setup the way it should be and when I did use the overlay in the past with the past version. Also I did try the Same Executable setting that you guys recommended to use and still was a black screen.

**Comment by EngineerMark** [comment]
This project is no longer under development.

Besides that, I got no clue what caused the issue between obs and osuachieved.

I might remake the program for the billionth time and hope it will work, but you are better off using respektive's [osu-tracker](https://github.com/respektive/osu-tracker)
